name: "Run system tests"
description: "Run system tests for the specified module"
inputs:
  module_name:
    description: "module name"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - run: echo "Hello ${{ inputs.module_name }}"
      shell: bash
